torch==2.8.0 -> torch==2.9.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.9.0 requires torch==2.9.0, but you have torch 2.8.0 which is incompatible.
torchvision 0.24.0 requires torch==2.9.0, but you have torch 2.8.0 which is incompatible.